### ISSUE TITLE
Output Image Contains Lower Resolution in Altered Object Area

### ISSUE THREAD

**Issue by ghost** [ali-vilab/MimicBrush#7]
-

**Comment by XavierCHEN34** [comment]
MimicBrush model deals with the input region under 512x512 and pastes back the generated results onto the high-res image. When the original image is much bigger than 512x512, the artifacts would be noticeable.  Other cases like a blurry reference image could also lead to this kind of result.  You could post your generated image here, I would see whether I have suggestions.

**Comment by MarsEverythingTech** [comment]
> MimicBrush model deals with the input region under 512x512 and pastes back the generated results onto the high-res image. When the original image is much bigger than 512x512, the artifacts would be noticeable. Other cases like a blurry reference image could also lead to this kind of result. You could post your generated image here, I would see whether I have suggestions.

Thank you for your prompt reply and explanation regarding the resolution handling of the MimicBrush model. I understand that the input region is limited to 512x512 and that the generated results are pasted back onto the high-resolution image.

Given this information, what solutions or recommendations do you have to mitigate the issue of lower resolution in the altered areas, especially when working with high-resolution images? Are there specific settings or techniques that could help enhance the quality of the altered regions?

Thank you for your assistance!

**Comment by XavierCHEN34** [comment]
I did not come up with some good suggestions because 4928x3264 is too big.  

If your editing region is not big, you might crop it region out ( like a region of 1024 x 1024), deal with this small region of MimicBrush, but paste it back to the full image. 

Otherwise, resize the image to around 1024, use MimicBrush, and find some tools for super resolution to resize it back to 4029. I hope these could help.
